development:
  clients:
    default:
      database: planner_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: planner_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
     uri: mongodb://username:password@host1:port1,host2:port2/database?replicaSet=<replicaSetName>

     options:
       connect_timeout: 15
