development:
  clients:
    default:
      database: planner_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: planner_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
    options:
      connect_timeout: 15
      database: planner_prod
